name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Update checkout to v4
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Update AWS Credentials to v4 (Fixes deprecation)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Update ECR Login to v2 (Fixes masking security warning)
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Build and Tag Docker Image
      - name: Build Docker Image
        run: |
          docker build -t my-app-repo .
          docker tag my-app-repo:latest ${{ steps.login-ecr.outputs.registry }}/my-app-repo:latest

      # 5. SCAN the image for vulnerabilities (Trivy)
      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-app-repo:latest'
          format: 'table'
          exit-code: '1' # This fails the pipeline if "CRITICAL" bugs are found
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      # 6. Push Image to AWS ECR
      - name: Push Image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/my-app-repo:latest

      # 7. Update Kubeconfig so we can talk to EKS
      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --name my-pipeline-cluster --region ${{ secrets.AWS_REGION }}

      # 8. Deploy to Kubernetes
      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s-deployment.yaml
          kubectl rollout restart deployment/my-app